CREATE TABLE "DEVOPS"."AIRPORT" 
   (	"CODE" VARCHAR2(3), 
	"NAME" VARCHAR2(255), 
	"CITY" NUMBER, 
	 CONSTRAINT "AIRPORT_PK" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "AIRPORT_CITY_FK" FOREIGN KEY ("CITY")
	  REFERENCES "DEVOPS"."CITY" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM";

INSERT INTO DEVOPS.AIRPORT (code, name, city) VALUES('BIO', 'Sondika', 3);
INSERT INTO DEVOPS.AIRPORT (code, name, city) VALUES('MAD', 'Adolfo Suarez', 2);
