apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.id }}
  labels:
    app: {{ .Values.id }}
spec:
  rules:
  - host: {{ .Values.phase }}.{{ .Values.id }}{{ .Values.suffix }}{{ .Values.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.id }}-{{ .Values.phase }}
          servicePort: 8080
