apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.id }}
  labels:
    app: {{ .Values.id }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: ingress-basic-auth
spec:
  rules:
  - host: {{ .Values.id }}{{ .Values.suffix }}.{{ .Values.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.id }}-{{ .Values.phase }}
          servicePort: 8080
  tls:
  - secretName: secure-tls
    hosts:
    - {{ .Values.id }}{{ .Values.suffix }}.{{ .Values.domain }}

