version: '3'

services:
  
  devops-app-master:
    image: nexus.tntformacion.com:10000/devops/app:0.0.12-SNAPSHOT
    environment:
      DATABASE_HOST: 'devops-db-master'
      DATABASE_PORT: '3306'
      DATABASE_NAME: 'devops'
      DATABASE_USER: 'devops'
      DATABASE_PASS: 'tec.82sup'
    links:
    - devops-db-master
    depends_on:
    - devops-db-master
    ports:
    - "8099:8080"
    networks:
    - devops_master

  devops-db-master:
    image: mysql:5.7
    volumes:
      - db_data_master:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'tec.82sup'
      MYSQL_DATABASE: 'devops'
      MYSQL_USER: 'devops'
      MYSQL_PASSWORD: 'tec.82sup'
    ports:
    - "3308:3306"
    networks:
    - devops_master

volumes:
  db_data_master:

networks:
  devops_master:
  