kind: PersistentVolume
apiVersion: v1
metadata:
  name: devops-airports-db-pv
  namespace: devops-airports-app
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"