apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devops-airports-db-pvc
  namespace: devops-airports-app
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi