apiVersion: v1
kind: Service
metadata:
  name: airports-db
  namespace: devops-app
spec:
  type: ClusterIP
  ports:
  - name: airports-db
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: airports-db